# Generated by Django 5.2.8 on 2025-11-22 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invites_available',
            field=models.PositiveIntegerField(default=3, help_text='Number of invites available'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique invitation code', max_length=32, unique=True)),
                ('recipient_email', models.EmailField(blank=True, help_text='Email of invited person (optional)', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', help_text='Status of invitation', max_length=20)),
                ('used_at', models.DateTimeField(blank=True, help_text='When this invitation was used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this invitation was created')),
                ('sender', models.ForeignKey(help_text='User who created this invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.OneToOneField(blank=True, help_text='User who accepted this invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitations',
                'ordering': ['-created_at'],
            },
        ),
    ]
