# Generated by Django 5.2.8 on 2025-11-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_invites_available_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invites_available',
        ),
    ]
