# Generated by Django 5.2.8 on 2025-11-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_invites_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invitation_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('founders_pass', "Founder's Pass")], default='normal', help_text='Type of invitation', max_length=20),
        ),
        migrations.AddField(
            model_name='invitation',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, help_text="Stripe coupon ID (for Founder's Pass)", max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='trial', help_text='Current subscription status', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When trial period ends', null=True),
        ),
    ]
