# Generated by Django 5.2.8 on 2025-11-22 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_link_remove_item_links_item_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='is_listed',
            field=models.BooleanField(default=True, help_text="Whether this guide appears on user's profile"),
        ),
        migrations.AlterField(
            model_name='guide',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the guide', null=True, upload_to='guide_covers/'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this guide was created'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this guide is about'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this guide is publicly accessible'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='owner',
            field=models.ForeignKey(help_text='User who created this guide', on_delete=django.db.models.deletion.CASCADE, related_name='guides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guide',
            name='password',
            field=models.CharField(blank=True, help_text='Password for password-protected guides', max_length=128),
        ),
        migrations.AlterField(
            model_name='guide',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of title', max_length=200),
        ),
        migrations.AlterField(
            model_name='guide',
            name='title',
            field=models.CharField(help_text='Title of the guide', max_length=200),
        ),
        migrations.AlterField(
            model_name='guide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this guide was last updated'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this item was created'),
        ),
        migrations.AlterField(
            model_name='item',
            name='guide',
            field=models.ForeignKey(help_text='Guide this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='guides.guide'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for this item', null=True, upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='links',
            field=models.ManyToManyField(blank=True, help_text='Links associated with this item', related_name='items', to='guides.link'),
        ),
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.TextField(blank=True, help_text='Why you love this item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Position of this item in the guide'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(help_text='Title of the item', max_length=300),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this item was last updated'),
        ),
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this link was created'),
        ),
        migrations.AlterField(
            model_name='link',
            name='label',
            field=models.CharField(blank=True, help_text='Display label for the link', max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(help_text='URL of the link', max_length=500),
        ),
    ]
