# Generated by Django 5.2.8 on 2025-11-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_guide_is_listed_alter_guide_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this guide was deleted', null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Whether this guide is soft-deleted'),
        ),
    ]
