# Generated by Django 5.2.8 on 2025-11-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_guide_deleted_at_guide_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this record was deleted', null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Whether this record is soft-deleted'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
    ]
